### ISSUE TITLE
Elaborate about runai-reservation namespace

### ISSUE THREAD

**Issue by doronkg** [run-ai/docs#179]
When installing Run:ai, a namespace is created as part of the cluster named `runai-reservation`.
This namespace is purposed to reserve GPUs that are used for jobs with fractional GPUs.

When a new job with fractional GPU is submitted, a new pod is created within `runai-reservation` namespace and is responsible for preventing the "full GPU" workload from using that GPU.

There is no reference for that namespace at all in the docs.
An official elaboration would be great :)

**Comment by yarongol** [comment]
Thank you Doron. Have added data. on runai-reservation in our upcoming 2.9 release https://github.com/run-ai/docs/blob/2.9/docs/Researcher/scheduling/fractions.md#runai-fractions
