### ISSUE TITLE
Typo in runai-submit-mpi.md

### ISSUE THREAD

**Issue by Warvito** [run-ai/docs#2]
There is a typo in  [docs/docs/Researcher/cli-reference/runai-submit-mpi.md](https://github.com/run-ai/docs/blob/master/docs/Researcher/cli-reference/runai-submit-mpi.md).

In Examples, there is a flag `--num-processes=2` where it should be `--processes=2`.

**Comment by yarongol** [comment]
Fixed. Thank you! @Warvito
