### ISSUE TITLE
WARN[0000] Error in getting user details: token is missing the 'username' claim 

### ISSUE THREAD

**Issue by wvxvw** [run-ai/docs#207]
Hello.

I'm trying to understand whether this is a configuration error on my part, or is this a problem with Run:ai.

I'm getting this warning in following contexts:

```sh
root@ose-t-u2004-02-28-1:~# ./runai-cli-linux-amd64 list jobs -p test1
WARN[0000] Error in getting user details: token is missing the 'username' claim 
ERRO[0000] project test1 does not exist. Run 'runai list project' to view all available projects 
root@ose-t-u2004-02-28-1:~# ./runai-cli-linux-amd64 list jobs -A
WARN[0000] Error in getting user details: token is missing the 'username' claim 
WARN[0000] Error in getting user details: token is missing the 'username' claim 
NAME  STATUS  AGE  NODE  IMAGE  TYPE  PROJECT  USER  GPUs Allocated (Requested)  PODs Running (Pending)  SERVICE URL(S)
```

As you can see, sometimes it results in error, and other times -- not so much.

Additionally, the jobs are actually running since:

```sh
root@ose-t-u2004-02-28-1:~# ./runai-cli-linux-amd64 describe job train1 -p test1 | head -5
WARN[0000] Error in getting user details: token is missing the 'username' claim 
Name: train1
Namespace: runai-test1
Type: Train
Status: Running
Duration: 9m
```

succeeds, but with the same warning.

Also, when trying to list projects, none of them are found:

```sh
root@ose-t-u2004-02-28-1:~# ./runai-cli-linux-amd64 list project                                                                                                                                                                            
WARN[0000] Error in getting user details: token is missing the 'username' claim 
PROJECT  DEPARTMENT  DESERVED GPUs  ALLOCATED GPUs  INT LIMIT  INT AFFINITY  TRAIN AFFINITY  MANAGED NAMESPACE
root@ose-t-u2004-02-28-1:~# 
```

Even though I was able to submit the job and execute `describe` on it.

So, what is going on?

----

NB. It would be nice if instead of the warning message being directed at developers, the message would convey useful information to the users (administrators are users for this purpose).  There's no way to understand for the user what token is this message talking about.

**Comment by SaraNachmias** [comment]
Thank you for reaching out. In order to help you we need some more information regarding the system you’re running. Can you give us some more information?
what runai version are you running?
what cli are you running? (./runai version)
what kubernetes flavor and version are you using? (openshift, rancher, etc)
can you run ./runai whoami and tell us what you see? it is possible that you need to run ./runai login

**Comment by wvxvw** [comment]
Hi. I can answer some questions now, but for others I'll have to re-deploy the cluster, so I'll answer them later (probably tomorrow).

1. I don't know what version of `runai` CLI I'm running. I pulled it out of the image, but didn't look at the version info.
2. I'm validating the integration created by (former Bright) NVidia. Another programmer worked on creating necessary Kubernetes / Helm configurations and I'm trying to use it to see if we didn't miss anything.
3. So, this also answer the question about Kubernetes: it's Bright's deployment.
4. I tried running `whoami` earlier and that didn't work. The message was something along the lines of "you have to log in first". Then, when I tried to log in, I was told that I am using certificate to authenticate (so, I assumed I could not log in).
