### ISSUE TITLE
VISIBLE=true does nothing useful

### ISSUE THREAD

**Issue by elgalu** [run-ai/docs#235]
This VISIBLE=true does nothing useful, perhaps remove to avoid confusion?

https://github.com/run-ai/docs/blob/d17df2115022ac47f3cc4e1b49f046dcce001683/quickstart/x-forwarding/docker/Dockerfile#L15-L16

**Comment by yarongol** [comment]
Removed. Thank you!

(also see https://stackoverflow.com/questions/36292317/why-set-visible-now-in-etc-profile)
