### ISSUE TITLE
Upgrade Run:ai Airgapped 2.8.X

### ISSUE THREAD

**Issue by doronkg** [run-ai/docs#245]
In Run:ai installation tar (for airgapped), you could find the following:

```
deploy/
|__...
|__runai-backend/
|__runai-backend-<version>.tgz
|__...
```

The `runai-backend` is an empty folder, while the `runai-backend-<version>.tgz` should be inside of it according to the [docs](https://docs.run.ai/admin/runai-setup/self-hosted/k8s/upgrade/):

```
helm upgrade runai-backend runai-backend/runai-backend-<version>.tgz -n \
    runai-backend  -f runai-backend-values.yaml
```

Therefore, the tar should be moved into it, or otherwise, the command in the docs should be changed to `./runai-backend-<version>.tgz` instead.

**Comment by yarongol** [comment]
You are correct. We will change the document to reflect this (in the next version probably)
