### ISSUE TITLE
v2.13/admin/runai-setup/self-hosted/k8s/additional-clusters/

### ISSUE THREAD

**Issue by jasonnovichRunAI** [run-ai/docs#398]
### Discussed in https://github.com/run-ai/docs/discussions/397

<div type='discussions-op-text'>

<sup>Originally posted by **giscus[bot]** July 12, 2023</sup>
# v2.13/admin/runai-setup/self-hosted/k8s/additional-clusters/

 | Installing additional Clusters |   Installation.     

https://docs.run.ai/v2.13/admin/runai-setup/self-hosted/k8s/additional-clusters/

</div>

**Comment by yarongol** [comment]
Prometheus comment -- fixed
Hybrid cluster of OCP and regular k8s -- ignoring for now. Its a scenario which is too complex.
