### ISSUE TITLE
RunAI CLI

### ISSUE THREAD

**Issue by petergro-hub** [run-ai/docs#78]
Opening an issue here as there isn't the possibility to open one in the RunAI CLI repository:

https://github.com/run-ai/runai-cli/releases
On your latest version 2.3.1 your install script copies 'charts' into the installation folder, however it is not present in the install files. For now I've copied over the 'charts' folder from your version 2.3.0 and it seems to work.

Additionally you're missing an uninstall option to remove the command line interface in a user friendly manner.

**Comment by keinanDaniel** [comment]
Thanks for opening the issue.

We have removed 2.3.1 release for now ,and will re-release it once it is working properly.
