### ISSUE TITLE
File `admin/admin-ui-setup/deployments.md` not found

### ISSUE THREAD

**Issue by IsQiao** [run-ai/docs#882]
https://docs.run.ai/latest/admin/admin-ui-setup/deployments.md

graveyard:
https://github.com/run-ai/docs/blob/c1862cc2e730df0056d2683092ab33d0e2c625c4/graveyard/deployments.md

**Comment by yarongol** [comment]
Thanks for the feedback. We are in the process of reorganizing our documentation. We hope to sort it out soon.
